sudo: required
services:
  - docker

before_install:
  - docker build -t sahilvma/docker-frontend -f Dockerfile.dev .


script:
  - docker run sahilvma/docker-frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-frontend"
  env: "DockerFrontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-455449888482"
  bucket_path: "docker-frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"